disable ci

diff --git a/.github/workflows/pulsar-ci.yaml b/.github/workflows/pulsar-ci.yaml
--- a/.github/workflows/pulsar-ci.yaml
+++ b/.github/workflows/pulsar-ci.yaml
@@ -1227,76 +1227,76 @@ jobs:
 #      - name: build package
 #        run: mvn -B clean package -DskipTests -T 1C -ntp
 
-  owasp-dep-check:
-    name: OWASP dependency check
-    runs-on: ubuntu-20.04
-    timeout-minutes: 120
-    needs: [ 'preconditions', 'integration-tests' ]
-    if: ${{ needs.preconditions.outputs.need_owasp == 'true' }}
-    env:
-      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
-    steps:
-      - name: checkout
-        uses: actions/checkout@v3
-
-      - name: Tune Runner VM
-        uses: ./.github/actions/tune-runner-vm
-
-      - name: Setup ssh access to build runner VM
-        # ssh access is enabled for builds in own forks
-        if: ${{ github.repository != 'apache/pulsar' && github.event_name == 'pull_request' }}
-        uses: ./.github/actions/ssh-access
-        continue-on-error: true
-        with:
-          limit-access-to-actor: true
-
-      - name: Cache Maven dependencies
-        uses: actions/cache@v3
-        timeout-minutes: 5
-        with:
-          path: |
-            ~/.m2/repository/*/*/*
-            !~/.m2/repository/org/apache/pulsar
-          key: ${{ runner.os }}-m2-dependencies-core-modules-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-m2-dependencies-core-modules-
-      - name: Set up JDK ${{ matrix.jdk || '17' }}
-        uses: actions/setup-java@v3
-        with:
-          distribution: 'temurin'
-          java-version: ${{ matrix.jdk || '17' }}
-
-      - name: Clean Disk
-        uses: ./.github/actions/clean-disk
-
-      - name: Install gh-actions-artifact-client.js
-        uses: apache/pulsar-test-infra/gh-actions-artifact-client/dist@master
-
-      - name: Restore maven build results from Github artifact cache
-        run: |
-          cd $HOME
-          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh restore_tar_from_github_actions_artifacts pulsar-maven-repository-binaries
-      # Projects dependent on flume, hdfs, hbase, and presto currently excluded from the scan.
-      - name: trigger dependency check
-        run: |
-          mvn -B -ntp verify -PskipDocker,skip-all,owasp-dependency-check -Dcheckstyle.skip=true -DskipTests \
-            -pl '!pulsar-sql,!distribution/server,!distribution/io,!distribution/offloaders,!pulsar-sql/presto-distribution,!tiered-storage/file-system,!pulsar-io/flume,!pulsar-io/hbase,!pulsar-io/hdfs2,!pulsar-io/hdfs3,!pulsar-io/docs,!pulsar-io/jdbc/openmldb'
-
-      - name: Upload report
-        uses: actions/upload-artifact@v3
-        if: ${{ cancelled() || failure() }}
-        continue-on-error: true
-        with:
-          name: dependency report
-          path: target/dependency-check-report.html
-
-      - name: Wait for ssh connection when build fails
-        # ssh access is enabled for builds in own forks
-        uses: ./.github/actions/ssh-access
-        if: ${{ failure() && github.repository != 'apache/pulsar' && github.event_name == 'pull_request' }}
-        continue-on-error: true
-        with:
-          action: wait
+#  owasp-dep-check:
+#    name: OWASP dependency check
+#    runs-on: ubuntu-20.04
+#    timeout-minutes: 120
+#    needs: [ 'preconditions', 'integration-tests' ]
+#    if: ${{ needs.preconditions.outputs.need_owasp == 'true' }}
+#    env:
+#      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
+#    steps:
+#      - name: checkout
+#        uses: actions/checkout@v3
+#
+#      - name: Tune Runner VM
+#        uses: ./.github/actions/tune-runner-vm
+#
+#      - name: Setup ssh access to build runner VM
+#        # ssh access is enabled for builds in own forks
+#        if: ${{ github.repository != 'apache/pulsar' && github.event_name == 'pull_request' }}
+#        uses: ./.github/actions/ssh-access
+#        continue-on-error: true
+#        with:
+#          limit-access-to-actor: true
+#
+#      - name: Cache Maven dependencies
+#        uses: actions/cache@v3
+#        timeout-minutes: 5
+#        with:
+#          path: |
+#            ~/.m2/repository/*/*/*
+#            !~/.m2/repository/org/apache/pulsar
+#          key: ${{ runner.os }}-m2-dependencies-core-modules-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: |
+#            ${{ runner.os }}-m2-dependencies-core-modules-
+#      - name: Set up JDK ${{ matrix.jdk || '17' }}
+#        uses: actions/setup-java@v3
+#        with:
+#          distribution: 'temurin'
+#          java-version: ${{ matrix.jdk || '17' }}
+#
+#      - name: Clean Disk
+#        uses: ./.github/actions/clean-disk
+#
+#      - name: Install gh-actions-artifact-client.js
+#        uses: apache/pulsar-test-infra/gh-actions-artifact-client/dist@master
+#
+#      - name: Restore maven build results from Github artifact cache
+#        run: |
+#          cd $HOME
+#          $GITHUB_WORKSPACE/build/pulsar_ci_tool.sh restore_tar_from_github_actions_artifacts pulsar-maven-repository-binaries
+#      # Projects dependent on flume, hdfs, hbase, and presto currently excluded from the scan.
+#      - name: trigger dependency check
+#        run: |
+#          mvn -B -ntp verify -PskipDocker,skip-all,owasp-dependency-check -Dcheckstyle.skip=true -DskipTests \
+#            -pl '!pulsar-sql,!distribution/server,!distribution/io,!distribution/offloaders,!pulsar-sql/presto-distribution,!tiered-storage/file-system,!pulsar-io/flume,!pulsar-io/hbase,!pulsar-io/hdfs2,!pulsar-io/hdfs3,!pulsar-io/docs,!pulsar-io/jdbc/openmldb'
+#
+#      - name: Upload report
+#        uses: actions/upload-artifact@v3
+#        if: ${{ cancelled() || failure() }}
+#        continue-on-error: true
+#        with:
+#          name: dependency report
+#          path: target/dependency-check-report.html
+#
+#      - name: Wait for ssh connection when build fails
+#        # ssh access is enabled for builds in own forks
+#        uses: ./.github/actions/ssh-access
+#        if: ${{ failure() && github.repository != 'apache/pulsar' && github.event_name == 'pull_request' }}
+#        continue-on-error: true
+#        with:
+#          action: wait
 
   # This job is required for pulls to be merged.
   # It depends on all other jobs in this workflow.
@@ -1310,13 +1310,13 @@ jobs:
       'preconditions',
       'unit-tests',
       'integration-tests',
-      'system-tests',
-      'flaky-system-tests',
-      'macos-build',
+#      'system-tests',
+#      'flaky-system-tests',
+#      'macos-build',
       'unit-tests-upload-coverage',
       'integration-tests-upload-coverage',
-      'system-tests-upload-coverage',
-      'owasp-dep-check'
+#      'system-tests-upload-coverage',
+#      'owasp-dep-check'
     ]
     steps:
       - name: Check that all required jobs were completed successfully
